### ISSUE TITLE
Bake author information into template

### ISSUE THREAD

**Issue by KingScooty** [KingScooty/kingscooty.github.io#29]
The old method seems to require the following YAML on every post, and it's unnecessary. Bake it into the template. 

```YAML
author:
  name: Scotty Vernon
  twitter: KingScooty
  gplus: +ScottyVernon 
  bio: Founder, Creative Technologist @ Wildflame Studios
  image: ks.png
```
